import type { Metadata } from "next";
import "@/styles/globals.css";
import { Provider } from "@/components/Provider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signInUrl="/auth">
      <html lang="en">
        <body className="min-h-dvh w-full">
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
